# See the documentation for more information:
# https://packit.dev/docs/configura

specfile_path: mesa.spec

downstream_package_name: mesa

files_to_sync:
  - mesa.spec
  - Mesa-MLAA-License-Clarification-Email.txt
  - packit.yaml

actions:
  # Create spec file from template
  post-upstream-clone:
    - bash -c "cp mesa.spec.template mesa.spec"
  get-current-version:
    - git submodule update --init
    - bash -c 'cd mesa && git log -n1 --date="format:%Y%m%d" --format="format:$(cut -d- -f1 < VERSION)~%cd^%h"'
  create-archive:
    - git submodule update --init
    - bash -c 'git ls-files --recurse-submodules | tar -caf mesa-nightly.tar.gz -T-'
    - echo 'mesa-nightly.tar.gz'
  # Use `fix-spec-file` to control Version-Release precisely
  fix-spec-file:
    - bash -c "sed -i -r \"s/Version:(\s*).*$/Version:\1${PACKIT_PROJECT_VERSION}/\" mesa.spec"
    - bash -c "(cd mesa && git log -n1 --date=format:\"%a %B %d %Y\" --format=format:\"* %cd packit <packit@asahilinux.org> - ${PACKIT_PROJECT_VERSION}-1%n\" && git log --since \"1 day ago\" --no-merges --pretty=\"format:- %s (%an)\" && echo) >> mesa.spec"

srpm_build_deps:
  - bash
  - curl
  - sed
  - cut

jobs:
- job: copr_build
  trigger: commit
  owner: "@asahi"
  project: mesa-nightly
  targets:
    - fedora-42-aarch64
    - fedora-42-i386
    - fedora-42-x86_64
    - fedora-rawhide-aarch64
    - fedora-rawhide-i386
    - fedora-rawhide-x86_64
